[platformio]
default_envs = prod

[env:prod]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	zinggjm/GxEPD2@^1.6.8
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.10.1
